### ISSUE TITLE
Latest version is not in pip

### ISSUE THREAD

**Issue by EmperorArthur** [m-a-k-o/django-mix#3]
Hello,

The latest changes to master are not reflected in the current `pip` download.

As such, the instructions regarding "LARAVELMIX_MANIFEST_DIRECTORY" do not work!

I would appreciate it if you could upload the latest version to pip.

**Comment by m-a-k-o** [comment]
Hello @EmperorArthur,

I will publish new version tomorrow.

Thank you!

**Comment by zodman** [comment]
+1

**Comment by zodman** [comment]
> Hello @EmperorArthur,
> 
> I will publish new version tomorrow.
> 
> Thank you!

pip install git+https://github.com/m-a-k-o/django-mix.git

**Comment by EmperorArthur** [comment]
> pip install git+https://github.com/m-a-k-o/django-mix.git

Yes, that is what I ended up doing.  However, there are a few negatives to that approach.  First, my Docker container now has to have git installed.  Second, this is the equivalent to running nightly.  It's not a development branch and should be stable, but it's still git master.

**Comment by m-a-k-o** [comment]
Latest version published on pypi. 

Sorry for delay :/
